name: ci
on: [push]
jobs:
  # run end-to-end tests using the standard workflow
  # https://github.com/bahmutov/cypress-workflows
  e2e:
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v1
    with:
      # use 4 containers
      n: 4
      build: npm run lint
      start: npm run start-18
      wait-on: 'http://127.0.0.1:3000'
      # merge code coverage into a single report
      coverage: true

  # in a separate job, run component tests
  # using the standard workflow
  # https://github.com/bahmutov/cypress-workflows
  components:
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
    with:
      component: true
